server:
  port: 8080
  session-timeout: 30
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8

spring :
  profiles :
    active : @activatedProperties@

spring:
  datasource :
    url : jdbc:mysql://10.71.254.151:3306/core
    username : root
    password : root
    type : com.alibaba.druid.pool.DruidDataSource
    driverClassName : com.mysql.jdbc.Driver
    initialSize :  5
    # 下面为连接池的补充设置，应用到上面所有数据源中
    minIdle : 5
    maxActive : 50
    # 配置获取连接等待超时的时间
    maxWait : 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis : 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis : 300000
    validationQuery : SELECT 1 FROM DUAL
    testWhileIdle : true
    testOnBorrow : false
    testOnReturn : false
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters : stat,wall,log4j
    logSlowSql : true

logging:
  pattern:
    console: "%d - %msg%n"
  path: D://
  file: D://demo.log

mybatis:
  config-location: classpath:mybatis-config.xml